# Node.js
# Build a Node.js project with Azure Pipelines.
# Add steps that publish artifacts, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
  displayName: 'npm build'
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '16.x'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'Azure subscription 1 (d4d0e9c4-0117-4691-b622-ffa3af4cd796)'
    appType: 'functionAppLinux'
    appName: 'edge-config'
    deployToSlotOrASE: true
    resourceGroupName: 'demo-learning'
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'NODE|16'