name: Node.js Environment

on:
  push:
    branches:
      - main

env:
  ENV_NAME: production

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm ci

      - name: Run tests
        run: |
          npm test
